set dotenv-required

default: build

build:
    dotnet build 'ModCode/ModMain/ModMain.csproj' '/property:Configuration=Release'

pack: build
    toi pack . -o "$MOD_PATH/{{file_name(justfile_directory())}}"
