set dotenv-required

default: build

build:
    if [ -f 'ModCode/ModMain/ModMain.csproj' ]; then \
        dotnet build -c Release 'ModCode/ModMain/ModMain.csproj'; \
    fi

pack: build
    toi mod pack . \
        -o "$MOD_PATH/{{file_name(justfile_directory())}}" \
        --clean \
        -g justfile
