set dotenv-required

default: build

build:
    dotnet build -c Release 'ModCode/ModMain/ModMain.csproj'

pack: build
    toi mod pack . \
        -o "$MOD_PATH/{{file_name(justfile_directory())}}" \
        --clean \
        -g justfile
