<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>MOD_Mivopx</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <AssetsSourceFiles Include="assets/**/*.*"/>
  </ItemGroup>
  <Target Name="CopyCustomContent" AfterTargets="AfterBuild">
    <Copy SourceFiles="@(AssetsSourceFiles)" DestinationFolder="$(OutDir)" SkipUnchangedFiles="true" />
  </Target>

  <ItemGroup>
    <PackageReference Include="UniverseLib.IL2CPP.Unhollower" Version="1.5.1" />
  </ItemGroup>
</Project>
