name: Release
run-name: Release ${{ inputs.mod-name || github.ref_name }}

on:
  push:
    tags:
      - "*/*"
  workflow_dispatch:
    inputs:
      mod-name:
        required: true
        type: string

jobs:
  build-mod:
    uses: ./.github/workflows/build-mod.yml
    with:
      mod-name: ${{ github.event.inputs.mod-name }}

  release:
    runs-on: ubuntu-latest
    needs: build-mod

    permissions:
      contents: write

    defaults:
      run:
        shell: pwsh

    steps:
      - uses: actions/checkout@v6

      - uses: actions/download-artifact@v8
        with:
          name: ${{ needs.build-mod.outputs.mod-name }}
          path: _publish/

      - name: Prepare package
        id: package
        run: |
          $PSNativeCommandUseErrorActionPreference = $true

          $modName = "${{ needs.build-mod.outputs.mod-name }}"
          $version = "${{ needs.build-mod.outputs.version }}"

          $package = "$modName-$version.zip"

          Compress-Archive "_publish/*" "$package"

          "package=$package" >> $env:GITHUB_OUTPUT

      - name: Prepare release description
        id: meta
        run: |
          $modPath = "${{ needs.build-mod.outputs.mod-path }}"

          $readmePath = "$modPath/README.md"

          $description = "No description"
          if (Test-Path $readmePath) {
            $description = "[Mod Description](./$readmePath)"
          }

          "description=$description" >> $env:GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.package.outputs.package }}
          tag_name: ${{ needs.build-mod.outputs.tag }}
          body: ${{ steps.meta.outputs.description }}
